# version: 1

# #database:
# #  host: "localhost"
# #  port: "5432"
# #  username: "ZmFpdA=="
# #  password: "RmFpdDIwMjQhIQ=="
# #  name: "dGVzdDU="

#   # DATABASE_URL = "postgresql://fait:Fait2024!!@localhost:5432/test5"
#   #  postgresql://[username]:[password]@[host]:[port]/[database]
#   # mongodb://fait_modb:Fait2024!!@localhost:27071/"

# mongodb:
#   host: "localhost"
#   port: 27017
#   username: "ZmFpdF9tb2Ri"
#   password: "RmFpdDIwMjQhIQ=="

# email:
#   email: "no-reply@firstaitutor.com"
#   password: "secure_password"


# database:
#   host: "localhost"
#   port: "5432"
#   username: "cG9zdGdyZXM="
#   password: "QFN1bmVlbDEq"
#   name: "cHJvamVjdA=="


database:
  internal_url: "postgresql://alco_sales_user:qkto580CDni5cyF0fGk6t3ijjsMlEkQw@dpg-cvv6tuqdbo4c73fgvisg-a/alco_sales"
  external_url: "postgresql://alco_sales_user:qkto580CDni5cyF0fGk6t3ijjsMlEkQw@dpg-cvv6tuqdbo4c73fgvisg-a.virginia-postgres.render.com/alco_sales"

email:
  email: "no-reply@firstaitutor.com"
  password: "secure_password"


